---
apiVersion: v1
kind: Pod
metadata:
  name: trail4
spec:
  initContainers:
    - name: alpine
      image: alpine
      args:
        - sleep
        - 30s
  containers:
    - name: httpd
      image: https

