---
apiVersion: v1
kind: Pod
metadata: 
  name: trail6
  labels:
    app: nginx
    env: dev
    version: "1.0"
spec:
  containers:
    - name: nginx
      image: nginx
      resources:
        limits:
          cpu: 1000m
          memory: 1000Mi
