---
apiVersion: v1
kind: Pod
metadata: 
  name: trail5
spec:
  initContainers:
    - name: alpine1
      image: alpine
      args:
        - sleep
        - 30s
    - name: alpine2
      image: alpine
      args:
        - sleep
        - 10s
    - name: alpine3
      image: alpine
      args:
        - sleep
        - 10s

  containers:
    - name: httpd
      image: httpd
      resources:
        limits:
          cpu: 1000m
          memory: 500Mi
    - name: nginx
      image: nginx
      resources:
        limits:
          cpu: 1000m
          memory: 500Mi

