---
apiVersion: v1
kind: Pod
metadata: 
  name: trail3
spec:
  containers:
    - name: httpd
      image: httpd
      resources:
        requests:
          cpu: 100m
          memory: 100Mi
        limits:
          cpu: 1000m
          memory: 1000Mi

