---
apiVersion: v1
kind: Pod
metadata:
  name: activity1
spec:
  containers:
    - name: httpd
      image: httpd
      ports:
        - containerPort: 80
      resources:
        requests:
          cpu: 100m
          memory: 100Mi
        limits:
          cpu: 1000m
          memory: 1000Mi
