---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: activity3
  labels:
    name: httpd
spec:
  minReadySeconds: 2
  replicas: 4
  selector: 
    matchLabels:
      app: httpd
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      name: httpd
      labels:
        app: httpd
        env: dev
    spec:
      containers:
        - name: httpd
          image: httpd
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 1000m
              memory: 1000Mi


---
apiVersion: v1	
kind: Service
metadata: 
  name: httpd-svc
  labels:
    app: httpd
spec:
  selector:
    app: httpd
  type: NodePort
  ports:
    - name: httpd
      nodePort: 32200
      port: 80
      targetPort: 80

